package org.kie.cloud.tests.services;

import java.util.UUID;

import lombok.extern.slf4j.Slf4j;
import org.kie.cloud.tests.core.context.Project;
import org.kie.cloud.tests.core.context.TestContext;
import org.kie.cloud.tests.environment.Environment;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class ProjectService {

	private static final String MDC_KEY = "project";

	@Autowired
    private Environment environment;

	@Value("${test.project.name.prefix}")
	private String projectNamePrefix;

	public Project createProject() {
		log.info("Creating project ... ");
		String autoGeneratedProjectName = projectNamePrefix + UUID.randomUUID().toString().substring(0, 4);
        Project project = environment.createProject(autoGeneratedProjectName);
		MDC.put(MDC_KEY, project.getName());
		log.info("Project created.");
		return project;
    }

	public void deleteProject(TestContext context) {
        if (context != null && context.getProject() != null) {
			log.debug("Deleting project ... ");
            environment.deleteProject(context.getProject());
			log.debug("Project deleted. ");
			MDC.remove(MDC_KEY);
		}

	}
}
